// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbfxwsbzrahrclnsqzec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZnh3c2J6cmFocmNsbnNxemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDkyNjksImV4cCI6MjA2MTAyNTI2OX0.K41km6Hcg4OeF0cASIM3M5Mzzet6LwsJ16cC9_t3prs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);